version: '3.4'

services:
  rc-frontend:
    container_name: nhsf-frontend
    env_file:
      - ./.env.local
    build:
      context: ./
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
